In [69]:
import pandas as pd

# Load the dataset
df = pd.read_csv('movies_dataset.csv')

C:\Users\ortol\AppData\Local\Temp\ipykernel_4312\2662559053.py:4: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('movies_dataset.csv')

### Display the first few rows of the dataset
df.head()
### Display information about the dataset
df.info()
### Display summary statistics of the dataset
df.describe()

In [70]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

            revenue       runtime  vote_average    vote_count
count  4.546000e+04  45203.000000  45460.000000  45460.000000
mean   1.120935e+07     94.128199      5.618207    109.897338
std    6.433225e+07     38.407810      1.924216    491.310374
min    0.000000e+00      0.000000      0.000000      0.000000
25%    0.000000e+00     85.000000      5.000000      3.000000
50%    0.000000e+00     95.000000      6.000000     10.000000
75%    0.000000e+00    107.000000      6.800000     34.000000
max    2.787965e+09   1256.000000     10.000000  14075.000000

In [71]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

The description looks a bit weird, it seems like the data needs to be normalized.
We can also see that there are a lot of missing values in the dataset.
Some columns are anidated, we need to check if we can flatten them.
Let's work on these issues.

In [72]:
print(df.isnull().sum())

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

Lests start deleting homepage that we are sure we are not going to need it lets see what we do with tagline and belongs_to_collection that they also have too many null values

In [73]:
df.drop('homepage', axis=1, inplace=True)

Know lets start working with the nested columns

In [74]:
import ast


# Función para desanidar listas y diccionarios en una sola columna de manera legible
def desanidar_columna_inteligente(df, columna):
    desanidado = []

    for item in df[columna]:
        if pd.isna(item) or item == '[]':
            desanidado.append('null')
        else:
            try:
                parsed_item = ast.literal_eval(item)
                # Verificar si es una lista de diccionarios
                if isinstance(parsed_item, list) and all(isinstance(i, dict) for i in parsed_item):
                    # Concatenar el campo 'name' de cada diccionario en una sola cadena
                    names = ', '.join([str(i.get('name', '')) for i in parsed_item])
                    desanidado.append(names if names else 'null')
                elif isinstance(parsed_item, dict):  # Caso de un diccionario único
                    name = parsed_item.get('name', 'null')
                    desanidado.append(name)
                else:
                    desanidado.append('null')
            except (ValueError, SyntaxError) as e:
                desanidado.append('null')

    return pd.Series(desanidado, name=columna)

# Lista de columnas anidadas que queremos desanidar
columnas_anidadas = ["belongs_to_collection", "genres", "production_companies"]

# Aplicar desanidación inteligente a cada columna anidada
for columna in columnas_anidadas:
    if columna in df.columns:
        df[columna] = desanidar_columna_inteligente(df, columna)

df.head()

,adult,belongs_to_collection,budget,genres,id,imdb_id,original_language,original_title,overview,popularity,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,Toy Story Collection,30000000,"Animation, Comedy, Family",862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,null,65000000,"Adventure, Fantasy, Family",8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,Grumpy Old Men Collection,0,"Romance, Comedy",15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,null,16000000,"Comedy, Drama, Romance",31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,Father of the Bride Collection,0,Comedy,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [75]:
df['production_companies'].head()

0                              Pixar Animation Studios
1    TriStar Pictures, Teitler Film, Interscope Com...
2                         Warner Bros., Lancaster Gate
3               Twentieth Century Fox Film Corporation
4           Sandollar Productions, Touchstone Pictures
Name: production_companies, dtype: object

In [76]:
df['spoken_languages'] = desanidar_columna_inteligente(df, 'spoken_languages')
df.head()

,adult,belongs_to_collection,budget,genres,id,imdb_id,original_language,original_title,overview,popularity,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,Toy Story Collection,30000000,"Animation, Comedy, Family",862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,...,1995-10-30,373554033.0,81.0,English,Released,NaN,Toy Story,False,7.7,5415.0
1,False,null,65000000,"Adventure, Fantasy, Family",8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,...,1995-12-15,262797249.0,104.0,"English, Français",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,Grumpy Old Men Collection,0,"Romance, Comedy",15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,...,1995-12-22,0.0,101.0,English,Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,null,16000000,"Comedy, Drama, Romance",31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,...,1995-12-22,81452156.0,127.0,English,Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,Father of the Bride Collection,0,Comedy,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,...,1995-02-10,76578911.0,106.0,English,Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

Lets know fill the null values of revenue and budget with 0

In [77]:
df['revenue'] = df['revenue'].fillna(0)
df['budget'] = df['budget'].fillna(0)

# Para verificar que se hayan rellenado correctamente, podemos hacer una comprobación:
print("Valores nulos en revenue:", df['revenue'].isnull().sum())
print("Valores nulos en budget:", df['budget'].isnull().sum())

# Ver algunos ejemplos de los datos actualizados
print("\nEjemplos de los datos:")
print(df[['revenue', 'budget']].head())

Valores nulos en revenue: 0
Valores nulos en budget: 0

Ejemplos de los datos:
       revenue    budget
0  373554033.0  30000000
1  262797249.0  65000000
2          0.0         0
3   81452156.0  16000000
4   76578911.0         0

In [78]:
# Primero, veamos cuántos valores nulos hay antes de eliminarlos
print("Cantidad de valores nulos en release_date antes:", df['release_date'].isnull().sum())
print("Cantidad total de filas antes:", len(df))

# Eliminar las filas donde release_date es nulo
df = df.dropna(subset=['release_date'])

# Verificar el resultado
print("\nCantidad de valores nulos en release_date después:", df['release_date'].isnull().sum())
print("Cantidad total de filas después:", len(df))

# Ver algunos ejemplos de las fechas
print("\nEjemplos de fechas:")
print(df['release_date'].head())

Cantidad de valores nulos en release_date antes: 87
Cantidad total de filas antes: 45466

Cantidad de valores nulos en release_date después: 0
Cantidad total de filas después: 45379

Ejemplos de fechas:
0    1995-10-30
1    1995-12-15
2    1995-12-22
3    1995-12-22
4    1995-02-10
Name: release_date, dtype: object

In [80]:
# 1. Convertir a datetime con manejo de errores
df['release_date'] = pd.to_datetime(df['release_date'], errors='coerce', format='mixed')

# 2. Convertir las fechas al formato deseado
df['release_date'] = df['release_date'].dt.strftime('%Y-%m-%d')

# 3. Crear la columna de año usando Int64 (que permite valores nulos)
df['release_year'] = pd.to_datetime(df['release_date']).dt.year.astype('Int64')

# 4. Verificar los resultados
print("\nEjemplos de fechas procesadas:")
print(df[['release_date', 'release_year']].head())

Ejemplos de fechas procesadas:
  release_date  release_year
0   1995-10-30          1995
1   1995-12-15          1995
2   1995-12-22          1995
3   1995-12-22          1995
4   1995-02-10          1995

In [83]:
import numpy as np

# 1. Primero convertimos budget a numérico usando pd.to_numeric
df['budget'] = pd.to_numeric(df['budget'], errors='coerce')

# 2. Ahora nos aseguramos que ambas columnas sean float
df['revenue'] = df['revenue'].astype(float)
df['budget'] = df['budget'].astype(float)

# 3. Rellenamos los NaN con 0
df['revenue'] = df['revenue'].fillna(0)
df['budget'] = df['budget'].fillna(0)

# 4. Creamos la columna return
df['return'] = df.apply(lambda row: 
    row['revenue'] / row['budget'] if row['budget'] != 0 
    else 0, axis=1)

# 5. Reemplazamos valores infinitos y NaN con 0
df['return'] = df['return'].replace([np.inf, -np.inf, np.nan], 0)

# 6. Verificamos los resultados
print("Tipos de datos después de la conversión:")
print(df[['revenue', 'budget', 'return']].dtypes)
print("\nPrimeros ejemplos:")
print(df[['revenue', 'budget', 'return']].head())

Tipos de datos después de la conversión:
revenue    float64
budget     float64
return     float64
dtype: object

Primeros ejemplos:
       revenue      budget     return
0  373554033.0  30000000.0  12.451801
1  262797249.0  65000000.0   4.043035
2          0.0         0.0   0.000000
3   81452156.0  16000000.0   5.090760
4   76578911.0         0.0   0.000000

In [84]:
# Lista de columnas a eliminar
columnas_a_eliminar = ['video', 'imdb_id', 'adult', 'original_title', 'poster_path']

# Eliminar las columnas
df = df.drop(columnas_a_eliminar, axis=1)

# Verificar las columnas restantes
print("Columnas restantes en el dataset:")
print(df.columns.tolist())

Columnas restantes en el dataset:
['belongs_to_collection', 'budget', 'genres', 'id', 'original_language', 'overview', 'popularity', 'production_companies', 'production_countries', 'release_date', 'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title', 'vote_average', 'vote_count', 'release_year', 'return']

Lets save the filtered df on a new csv file

In [85]:
df.to_csv('movies_limpio.csv', 
          index=False,
          encoding='utf-8',
          sep=',')

Lets work with the other file credits now

In [86]:
df = pd.read_csv('credits.csv')

In [87]:
df.head()

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862

In [89]:
df.isnull().sum()

cast    0
crew    0
id      0
dtype: int64

In [93]:
df.iloc[0,1]

'[{\'credit_id\': \'52fe4284c3a36847f8024f49\', \'department\': \'Directing\', \'gender\': 2, \'id\': 7879, \'job\': \'Director\', \'name\': \'John Lasseter\', \'profile_path\': \'/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f4f\', \'department\': \'Writing\', \'gender\': 2, \'id\': 12891, \'job\': \'Screenplay\', \'name\': \'Joss Whedon\', \'profile_path\': \'/dTiVsuaTVTeGmvkhcyJvKp2A5kr.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f55\', \'department\': \'Writing\', \'gender\': 2, \'id\': 7, \'job\': \'Screenplay\', \'name\': \'Andrew Stanton\', \'profile_path\': \'/pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f5b\', \'department\': \'Writing\', \'gender\': 2, \'id\': 12892, \'job\': \'Screenplay\', \'name\': \'Joel Cohen\', \'profile_path\': \'/dAubAiZcvKFbboWlj7oXOkZnTSu.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f61\', \'department\': \'Writing\', \'gender\': 0, \'id\': 12893, \'job\': \'Screenplay\', \'name\': \'Alec Sokolow\', \'profile_path\': \'/v79vlRYi94BZUQnkkyznbGUZLjT.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f67\', \'department\': \'Production\', \'gender\': 1, \'id\': 12894, \'job\': \'Producer\', \'name\': \'Bonnie Arnold\', \'profile_path\': None}, {\'credit_id\': \'52fe4284c3a36847f8024f6d\', \'department\': \'Production\', \'gender\': 0, \'id\': 12895, \'job\': \'Executive Producer\', \'name\': \'Ed Catmull\', \'profile_path\': None}, {\'credit_id\': \'52fe4284c3a36847f8024f73\', \'department\': \'Production\', \'gender\': 2, \'id\': 12896, \'job\': \'Producer\', \'name\': \'Ralph Guggenheim\', \'profile_path\': None}, {\'credit_id\': \'52fe4284c3a36847f8024f79\', \'department\': \'Production\', \'gender\': 2, \'id\': 12897, \'job\': \'Executive Producer\', \'name\': \'Steve Jobs\', \'profile_path\': \'/mOMP3SwD5qWQSR0ldCIByd3guTV.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f8b\', \'department\': \'Editing\', \'gender\': 2, \'id\': 8, \'job\': \'Editor\', \'name\': \'Lee Unkrich\', \'profile_path\': \'/bdTCCXjgOV3YyaNmLGYGOxFQMOc.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f91\', \'department\': \'Art\', \'gender\': 2, \'id\': 7883, \'job\': \'Art Direction\', \'name\': \'Ralph Eggleston\', \'profile_path\': \'/uUfcGKDsKO1aROMpXRs67Hn6RvR.jpg\'}, {\'credit_id\': \'598331bf925141421201044b\', \'department\': \'Editing\', \'gender\': 2, \'id\': 1168870, \'job\': \'Editor\', \'name\': \'Robert Gordon\', \'profile_path\': None}, {\'credit_id\': \'5892168cc3a36809660095f9\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1552883, \'job\': \'Foley Editor\', \'name\': \'Mary Helen Leasman\', \'profile_path\': None}, {\'credit_id\': \'5531824d9251415289000945\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1453514, \'job\': \'Animation\', \'name\': \'Kim Blanchette\', \'profile_path\': None}, {\'credit_id\': \'589215969251412dcb009bf6\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1414182, \'job\': \'ADR Editor\', \'name\': \'Marilyn McCoppen\', \'profile_path\': None}, {\'credit_id\': \'589217099251412dc500a018\', \'department\': \'Sound\', \'gender\': 2, \'id\': 7885, \'job\': \'Orchestrator\', \'name\': \'Randy Newman\', \'profile_path\': \'/w0JzfoiM25nrnxYOzosPHRq6mlE.jpg\'}, {\'credit_id\': \'5693e6b29251417b0e0000e3\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1429549, \'job\': \'Color Timer\', \'name\': \'Dale E. Grahn\', \'profile_path\': None}, {\'credit_id\': \'572e2522c3a36869e6001a9c\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 7949, \'job\': \'CG Painter\', \'name\': \'Robin Cooper\', \'profile_path\': None}, {\'credit_id\': \'574f12309251415ca1000012\', \'department\': \'Writing\', \'gender\': 2, \'id\': 7879, \'job\': \'Original Story\', \'name\': \'John Lasseter\', \'profile_path\': \'/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg\'}, {\'credit_id\': \'574f1240c3a3682e7300001c\', \'department\': \'Writing\', \'gender\': 2, \'id\': 12890, \'job\': \'Original Story\', \'name\': \'Pete Docter\', \'profile_path\': \'/r6ngPgnReA3RHmKjmSoVsc6Awjp.jpg\'}, {\'credit_id\': \'574f12519251415c92000015\', \'department\': \'Writing\', \'gender\': 0, \'id\': 7911, \'job\': \'Original Story\', \'name\': \'Joe Ranft\', \'profile_path\': \'/f1BoWC2JbCcfP1e5hKfGsxkHzVU.jpg\'}, {\'credit_id\': \'574f12cec3a3682e82000022\', \'department\': \'Crew\', \'gender\': 0, \'id\': 1629419, \'job\': \'Post Production Supervisor\', \'name\': \'Patsy Bouge\', \'profile_path\': None}, {\'credit_id\': \'574f14f19251415ca1000082\', \'department\': \'Art\', \'gender\': 0, \'id\': 7961, \'job\': \'Sculptor\', \'name\': \'Norm DeCarlo\', \'profile_path\': None}, {\'credit_id\': \'5751ae4bc3a3683772002b7f\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 12905, \'job\': \'Animation Director\', \'name\': \'Ash Brannon\', \'profile_path\': \'/6ueWgPEEBHvS3De2BHYQnYjRTig.jpg\'}, {\'credit_id\': \'5891edbe9251412dc5007cd6\', \'department\': \'Sound\', \'gender\': 2, \'id\': 7885, \'job\': \'Music\', \'name\': \'Randy Newman\', \'profile_path\': \'/w0JzfoiM25nrnxYOzosPHRq6mlE.jpg\'}, {\'credit_id\': \'589213d39251412dc8009832\', \'department\': \'Directing\', \'gender\': 0, \'id\': 1748707, \'job\': \'Layout\', \'name\': \'Roman Figun\', \'profile_path\': None}, {\'credit_id\': \'5892173dc3a3680968009351\', \'department\': \'Sound\', \'gender\': 2, \'id\': 4949, \'job\': \'Orchestrator\', \'name\': \'Don Davis\', \'profile_path\': None}, {\'credit_id\': \'589217cec3a3686b0a0052ba\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1372885, \'job\': \'Music Editor\', \'name\': \'James Flamberg\', \'profile_path\': None}, {\'credit_id\': \'58921831c3a3686348004a64\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1739962, \'job\': \'Negative Cutter\', \'name\': \'Mary Beth Smith\', \'profile_path\': None}, {\'credit_id\': \'58921838c3a36809700096c0\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1748513, \'job\': \'Negative Cutter\', \'name\': \'Rick Mackay\', \'profile_path\': None}, {\'credit_id\': \'589218429251412dd1009d1b\', \'department\': \'Art\', \'gender\': 0, \'id\': 1458006, \'job\': \'Title Designer\', \'name\': \'Susan Bradley\', \'profile_path\': None}, {\'credit_id\': \'5891ed99c3a3680966007670\', \'department\': \'Crew\', \'gender\': 0, \'id\': 1748557, \'job\': \'Supervising Technical Director\', \'name\': \'William Reeves\', \'profile_path\': None}, {\'credit_id\': \'5891edcec3a3686b0a002eb2\', \'department\': \'Sound\', \'gender\': 2, \'id\': 7885, \'job\': \'Songs\', \'name\': \'Randy Newman\', \'profile_path\': \'/w0JzfoiM25nrnxYOzosPHRq6mlE.jpg\'}, {\'credit_id\': \'5891edf9c3a36809700075e6\', \'department\': \'Writing\', \'gender\': 2, \'id\': 7, \'job\': \'Original Story\', \'name\': \'Andrew Stanton\', \'profile_path\': \'/pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg\'}, {\'credit_id\': \'58920f0b9251412dd7009104\', \'department\': \'Crew\', \'gender\': 2, \'id\': 12890, \'job\': \'Supervising Animator\', \'name\': \'Pete Docter\', \'profile_path\': \'/r6ngPgnReA3RHmKjmSoVsc6Awjp.jpg\'}, {\'credit_id\': \'58920f1fc3a3680977009021\', \'department\': \'Sound\', \'gender\': 2, \'id\': 2216, \'job\': \'Sound Designer\', \'name\': \'Gary Rydstrom\', \'profile_path\': \'/jZpr1nVfO7lldWI0YtmP1FGw7Rj.jpg\'}, {\'credit_id\': \'58920f389251412dd700912d\', \'department\': \'Production\', \'gender\': 0, \'id\': 12909, \'job\': \'Production Supervisor\', \'name\': \'Karen Robert Jackson\', \'profile_path\': None}, {\'credit_id\': \'58920fbd9251412dcb00969c\', \'department\': \'Crew\', \'gender\': 0, \'id\': 953331, \'job\': \'Executive Music Producer\', \'name\': \'Chris Montan\', \'profile_path\': None}, {\'credit_id\': \'589210069251412dd7009219\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 7893, \'job\': \'Animation Director\', \'name\': \'Rich Quade\', \'profile_path\': None}, {\'credit_id\': \'589210329251412dcd00943b\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8025, \'job\': \'Animation\', \'name\': \'Michael Berenstein\', \'profile_path\': None}, {\'credit_id\': \'5892103bc3a368096a009180\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 78009, \'job\': \'Animation\', \'name\': \'Colin Brady\', \'profile_path\': None}, {\'credit_id\': \'5892105dc3a3680968008db2\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748682, \'job\': \'Animation\', \'name\': \'Davey Crockett Feiten\', \'profile_path\': None}, {\'credit_id\': \'589210669251412dcd009466\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1454030, \'job\': \'Animation\', \'name\': \'Angie Glocka\', \'profile_path\': None}, {\'credit_id\': \'5892107c9251412dd1009613\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748683, \'job\': \'Animation\', \'name\': \'Rex Grignon\', \'profile_path\': None}, {\'credit_id\': \'5892108ac3a3680973008d3f\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748684, \'job\': \'Animation\', \'name\': \'Tom K. Gurney\', \'profile_path\': None}, {\'credit_id\': \'58921093c3a3686348004477\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 8029, \'job\': \'Animation\', \'name\': \'Jimmy Hayward\', \'profile_path\': \'/lTDRpudEY7BDwTefXbXzMlmb0ui.jpg\'}, {\'credit_id\': \'5892109b9251412dcd0094b0\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1426773, \'job\': \'Animation\', \'name\': \'Hal T. Hickel\', \'profile_path\': None}, {\'credit_id\': \'589210a29251412dc5009a29\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8035, \'job\': \'Animation\', \'name\': \'Karen Kiser\', \'profile_path\': None}, {\'credit_id\': \'589210ccc3a3680977009191\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748688, \'job\': \'Animation\', \'name\': \'Anthony B. LaMolinara\', \'profile_path\': None}, {\'credit_id\': \'589210d7c3a3686b0a004c1f\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 587314, \'job\': \'Animation\', \'name\': \'Guionne Leroy\', \'profile_path\': None}, {\'credit_id\': \'589210e1c3a36809770091a7\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7918, \'job\': \'Animation\', \'name\': \'Bud Luckey\', \'profile_path\': \'/pcCh7G19FKMNijmPQg1PMH1btic.jpg\'}, {\'credit_id\': \'589210ee9251412dc200978a\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748689, \'job\': \'Animation\', \'name\': \'Les Major\', \'profile_path\': None}, {\'credit_id\': \'589210fa9251412dc8009595\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7892, \'job\': \'Animation\', \'name\': \'Glenn McQueen\', \'profile_path\': None}, {\'credit_id\': \'589211029251412dc8009598\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 555795, \'job\': \'Animation\', \'name\': \'Mark Oftedal\', \'profile_path\': None}, {\'credit_id\': \'5892110b9251412dc800959d\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7882, \'job\': \'Animation\', \'name\': \'Jeff Pidgeon\', \'profile_path\': \'/yLddkg5HcgbJg00cS13GVBnP0HY.jpg\'}, {\'credit_id\': \'58921113c3a36863480044e4\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8017, \'job\': \'Animation\', \'name\': \'Jeff Pratt\', \'profile_path\': None}, {\'credit_id\': \'5892111c9251412dcb0097e9\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1184140, \'job\': \'Animation\', \'name\': \'Steve Rabatich\', \'profile_path\': None}, {\'credit_id\': \'58921123c3a36809700090f6\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8049, \'job\': \'Animation\', \'name\': \'Roger Rose\', \'profile_path\': None}, {\'credit_id\': \'5892112b9251412dcb0097fb\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1509559, \'job\': \'Animation\', \'name\': \'Steve Segal\', \'profile_path\': None}, {\'credit_id\': \'589211349251412dc80095c3\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748691, \'job\': \'Animation\', \'name\': \'Doug Sheppeck\', \'profile_path\': None}, {\'credit_id\': \'5892113cc3a3680970009106\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8050, \'job\': \'Animation\', \'name\': \'Alan Sperling\', \'profile_path\': None}, {\'credit_id\': \'58921148c3a3686b0a004c99\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8010, \'job\': \'Animation\', \'name\': \'Doug Sweetland\', \'profile_path\': None}, {\'credit_id\': \'58921150c3a3680966009125\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8044, \'job\': \'Animation\', \'name\': \'David Tart\', \'profile_path\': None}, {\'credit_id\': \'589211629251412dc5009b00\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1454034, \'job\': \'Animation\', \'name\': \'Ken Willard\', \'profile_path\': None}, {\'credit_id\': \'589211c1c3a3686b0a004d28\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 7887, \'job\': \'Visual Effects Supervisor\', \'name\': \'Thomas Porter\', \'profile_path\': None}, {\'credit_id\': \'589211d4c3a3680968008ed9\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1406878, \'job\': \'Visual Effects\', \'name\': \'Mark Thomas Henne\', \'profile_path\': None}, {\'credit_id\': \'589211f59251412dd4008e65\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748698, \'job\': \'Visual Effects\', \'name\': \'Oren Jacob\', \'profile_path\': None}, {\'credit_id\': \'58921242c3a368096a00939b\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748699, \'job\': \'Visual Effects\', \'name\': \'Darwyn Peachey\', \'profile_path\': None}, {\'credit_id\': \'5892124b9251412dc5009bd2\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748701, \'job\': \'Visual Effects\', \'name\': \'Mitch Prater\', \'profile_path\': None}, {\'credit_id\': \'58921264c3a3686b0a004dbf\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748703, \'job\': \'Visual Effects\', \'name\': \'Brian M. Rosen\', \'profile_path\': None}, {\'credit_id\': \'589212709251412dcd009676\', \'department\': \'Lighting\', \'gender\': 1, \'id\': 12912, \'job\': \'Lighting Supervisor\', \'name\': \'Sharon Calahan\', \'profile_path\': None}, {\'credit_id\': \'5892127fc3a3686b0a004de5\', \'department\': \'Lighting\', \'gender\': 0, \'id\': 7899, \'job\': \'Lighting Supervisor\', \'name\': \'Galyn Susman\', \'profile_path\': None}, {\'credit_id\': \'589212cdc3a3680970009268\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 12915, \'job\': \'CG Painter\', \'name\': \'William Cone\', \'profile_path\': None}, {\'credit_id\': \'5892130f9251412dc8009791\', \'department\': \'Art\', \'gender\': 0, \'id\': 1748705, \'job\': \'Sculptor\', \'name\': \'Shelley Daniels Lekven\', \'profile_path\': None}, {\'credit_id\': \'5892131c9251412dd4008f4c\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7889, \'job\': \'Character Designer\', \'name\': \'Bob Pauley\', \'profile_path\': None}, {\'credit_id\': \'589213249251412dd100987b\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7918, \'job\': \'Character Designer\', \'name\': \'Bud Luckey\', \'profile_path\': \'/pcCh7G19FKMNijmPQg1PMH1btic.jpg\'}, {\'credit_id\': \'5892132b9251412dc80097b1\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7, \'job\': \'Character Designer\', \'name\': \'Andrew Stanton\', \'profile_path\': \'/pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg\'}, {\'credit_id\': \'58921332c3a368634800467b\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 12915, \'job\': \'Character Designer\', \'name\': \'William Cone\', \'profile_path\': None}, {\'credit_id\': \'5892135f9251412dd4008f90\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748706, \'job\': \'Character Designer\', \'name\': \'Steve Johnson\', \'profile_path\': None}, {\'credit_id\': \'58921384c3a3680973008fd4\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1176752, \'job\': \'Character Designer\', \'name\': \'Dan Haskett\', \'profile_path\': None}, {\'credit_id\': \'5892138e9251412dc20099fc\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1088034, \'job\': \'Character Designer\', \'name\': \'Tom Holloway\', \'profile_path\': \'/a0r0T2usTBpgMI5aZbRBDW1fTl8.jpg\'}, {\'credit_id\': \'58921395c3a368097700942f\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1447465, \'job\': \'Character Designer\', \'name\': \'Jean Gillmore\', \'profile_path\': None}, {\'credit_id\': \'589213e2c3a3680973009026\', \'department\': \'Directing\', \'gender\': 0, \'id\': 1748709, \'job\': \'Layout\', \'name\': \'Desirée Mourad\', \'profile_path\': None}, {\'credit_id\': \'589214099251412dc5009d57\', \'department\': \'Art\', \'gender\': 0, \'id\': 1748710, \'job\': \'Set Dresser\', \'name\': "Kelly O\'Connell", \'profile_path\': None}, {\'credit_id\': \'58921411c3a3686b0a004f70\', \'department\': \'Art\', \'gender\': 0, \'id\': 1443471, \'job\': \'Set Dresser\', \'name\': \'Sonoko Konishi\', \'profile_path\': None}, {\'credit_id\': \'58921434c3a368096a00956e\', \'department\': \'Art\', \'gender\': 0, \'id\': 1748711, \'job\': \'Set Dresser\', \'name\': \'Ann M. Rockwell\', \'profile_path\': None}, {\'credit_id\': \'5892144ac3a36809680090de\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1748712, \'job\': \'Editorial Manager\', \'name\': \'Julie M. McDonald\', \'profile_path\': None}, {\'credit_id\': \'58921479c3a368096800910f\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1589729, \'job\': \'Assistant Editor\', \'name\': \'Robin Lee\', \'profile_path\': None}, {\'credit_id\': \'5892148b9251412dd10099cc\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1748716, \'job\': \'Assistant Editor\', \'name\': \'Tom Freeman\', \'profile_path\': None}, {\'credit_id\': \'589214959251412dcb009b1f\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1748717, \'job\': \'Assistant Editor\', \'name\': \'Ada Cochavi\', \'profile_path\': None}, {\'credit_id\': \'5892149ec3a3686348004798\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1336438, \'job\': \'Assistant Editor\', \'name\': \'Dana Mulligan\', \'profile_path\': None}, {\'credit_id\': \'589214adc3a368096a0095db\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1748718, \'job\': \'Editorial Coordinator\', \'name\': \'Deirdre Morrison\', \'profile_path\': None}, {\'credit_id\': \'589214c7c3a368097700952b\', \'department\': \'Production\', \'gender\': 0, \'id\': 1748719, \'job\': \'Production Coordinator\', \'name\': \'Lori Lombardo\', \'profile_path\': None}, {\'credit_id\': \'589214cec3a368096a009603\', \'department\': \'Production\', \'gender\': 0, \'id\': 1748720, \'job\': \'Production Coordinator\', \'name\': \'Ellen Devine\', \'profile_path\': None}, {\'credit_id\': \'589214e39251412dc8009904\', \'department\': \'Crew\', \'gender\': 0, \'id\': 1468014, \'job\': \'Unit Publicist\', \'name\': \'Lauren Beth Strogoff\', \'profile_path\': None}, {\'credit_id\': \'58921544c3a3686b0a00507d\', \'department\': \'Sound\', \'gender\': 2, \'id\': 2216, \'job\': \'Sound Re-Recording Mixer\', \'name\': \'Gary Rydstrom\', \'profile_path\': \'/jZpr1nVfO7lldWI0YtmP1FGw7Rj.jpg\'}, {\'credit_id\': \'5892154c9251412dd1009a56\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1425978, \'job\': \'Sound Re-Recording Mixer\', \'name\': \'Gary Summers\', \'profile_path\': None}, {\'credit_id\': \'58921555c3a36809680091bd\', \'department\': \'Sound\', \'gender\': 2, \'id\': 8276, \'job\': \'Supervising Sound Editor\', \'name\': \'Tim Holland\', \'profile_path\': None}, {\'credit_id\': \'589215c39251412dcb009c12\', \'department\': \'Sound\', \'gender\': 0, \'id\': 7069, \'job\': \'Sound Effects Editor\', \'name\': \'Pat Jackson\', \'profile_path\': None}, {\'credit_id\': \'58921698c3a368096a009788\', \'department\': \'Crew\', \'gender\': 2, \'id\': 15894, \'job\': \'Sound Design Assistant\', \'name\': \'Tom Myers\', \'profile_path\': None}, {\'credit_id\': \'589216a89251412dc2009ca4\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1414177, \'job\': \'Assistant Sound Editor\', \'name\': \'J.R. 

Lets convert the cast column into its oun data frame

In [94]:
import json
# Función para expandir el cast en un nuevo DataFrame
def expandir_cast(df):
    registros_cast = []

    for _, row in df.iterrows():
        movie_id = row['id']
        try:
            # Convertir el valor en JSON válido
            cast_list = json.loads(row['cast'].replace("'", '"'))
            for actor in cast_list:
                # Agregar una fila con los datos de interés y excluir `credit_id` y `profile_path`
                registros_cast.append({
                    'movie_id': movie_id,
                    'actor_id': actor.get('id'),
                    'name': actor.get('name'),
                    'character': actor.get('character'),
                    'gender': actor.get('gender'),
                    'order': actor.get('order')
                })
        except (json.JSONDecodeError, TypeError):
            continue  # Omitir si no es posible procesar el JSON

    # Crear un nuevo DataFrame con los registros del cast
    return pd.DataFrame(registros_cast)

# Aplicar la función y crear el DataFrame del cast
df_cast = expandir_cast(df)

# Ver el resultado
print(df_cast)

       movie_id  actor_id             name                     character  \
0         15602      6837   Walter Matthau                   Max Goldman
1         15602      3151      Jack Lemmon                John Gustafson
2         15602     13567      Ann-Margret               Ariel Gustafson
3         15602     16757     Sophia Loren  Maria Sophia Coletta Ragetti
4         15602       589     Daryl Hannah             Melanie Gustafson
...         ...       ...              ...                           ...
63020     30840     29459   Patrick Bergin               Sir Robert Hode
63021     30840       139      Uma Thurman                   Maid Marian
63022     30840     18616  David Morrissey                   Little John
63023     30840       920  Jürgen Prochnow            Sir Miles Folcanet
63024     30840      1924    Jeroen Krabbé          Baron Roger Daguerre

       gender  order
0           2      0
1           2      1
2           1      2
3           1      3
4           1      4
...       ...    ...
63020       2      0
63021       1      1
63022       2      2
63023       2      3
63024       0      4

[63025 rows x 6 columns]

In [96]:
df_cast.isnull().sum()

movie_id     0
actor_id     0
name         0
character    0
gender       0
order        0
dtype: int64

In [97]:
df_cast.to_csv('movies_cast.csv', 
          index=False,
          encoding='utf-8',
          sep=',')

Lets do the same with the crew column

In [98]:
def expandir_crew(df):
    registros_crew = []

    for _, row in df.iterrows():
        movie_id = row['id']
        try:
            # Convertir el valor en JSON válido
            crew_list = json.loads(row['crew'].replace("'", '"'))
            for miembro in crew_list:
                # Agregar una fila con los datos de interés y excluir `credit_id` y `profile_path`
                registros_crew.append({
                    'movie_id': movie_id,
                    'crew_id': miembro.get('id'),
                    'name': miembro.get('name'),
                    'department': miembro.get('department'),
                    'job': miembro.get('job'),
                    'gender': miembro.get('gender')
                })
        except (json.JSONDecodeError, TypeError):
            continue  # Omitir si no es posible procesar el JSON

    # Crear un nuevo DataFrame con los registros del crew
    return pd.DataFrame(registros_crew)

# Aplicar la función y crear el DataFrame del crew
df_crew = expandir_crew(df)

# Ver el resultado
print(df_crew)

      movie_id  crew_id                 name department           job  gender
0        16420     6210  William Shakespeare    Writing        Writer       2
1        16420    56710        Oliver Parker  Directing      Director       2
2        16420    56710        Oliver Parker    Writing    Adaptation       2
3        31174    33315    Richard Loncraine  Directing      Director       2
4        31174     6210  William Shakespeare    Writing  Theatre Play       2
...        ...      ...                  ...        ...           ...     ...
8330    106807    11523       Georges Méliès  Directing      Director       0
8331     67179    20875          Leo Tolstoy    Writing         Novel       2
8332     67179    24279        Paolo Taviani    Writing    Screenplay       2
8333     67179    24279        Paolo Taviani  Directing      Director       2
8334     67179    24281     Vittorio Taviani  Directing      Director       0

[8335 rows x 6 columns]

In [99]:
df_cast.isnull().sum()

movie_id     0
actor_id     0
name         0
character    0
gender       0
order        0
dtype: int64

In [100]:
df_cast.to_csv('movies_crew.csv', 
          index=False,
          encoding='utf-8',
          sep=',')

Lets analize the movies file that we are going to use to train the model

In [101]:
from ydata_profiling import ProfileReport

# Cargar el dataset
df = pd.read_csv("movies_limpio.csv")

# Crear el informe de perfil
profile = ProfileReport(df, title="Análisis Exploratorio del Dataset", explorative=True)

profile.to_file("informe_analisis_exploratorio.html")

C:\Users\ortol\AppData\Roaming\Python\Python312\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
C:\Users\ortol\AppData\Local\Temp\ipykernel_4312\712701454.py:4: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("movies_limpio.csv")
Summarize dataset: 100%|██████████| 79/79 [00:32<00:00,  2.45it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:22<00:00, 22.09s/it]
Render HTML: 100%|██████████| 1/1 [00:04<00:00,  4.42s/it]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 25.00it/s]

Data profileing created for us a analycis report of the data that is pretty intresting and we can find it on the html on the filetree

## Data prep for coseno model
We are going to pass the natural lenguage columns and convet them on vectors so the model can recomend the most similar movies.

In [102]:
df = pd.read_csv('movies_limpio.csv')

df['text'] = (
    df['title'].fillna('') + ' ' + 
    df['genres'].fillna('') + ' ' + 
    df['overview'].fillna('') + ' ' + 
    df['tagline'].fillna('')
)

df['text'].head()

C:\Users\ortol\AppData\Local\Temp\ipykernel_4312\1181438895.py:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('movies_limpio.csv')

0    Toy Story Animation, Comedy, Family Led by Woo...
1    Jumanji Adventure, Fantasy, Family When siblin...
2    Grumpier Old Men Romance, Comedy A family wedd...
3    Waiting to Exhale Comedy, Drama, Romance Cheat...
4    Father of the Bride Part II Comedy Just when G...
Name: text, dtype: object

In [103]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Inicializamos el vectorizador TF-IDF, eliminando stopwords en inglés
tfidf_vectorizer = TfidfVectorizer(stop_words='english')

# Vectorización del texto de la columna unificada
tfidf_matrix = tfidf_vectorizer.fit_transform(df['text'])

Lets save the just generated vectors on a new file

In [104]:
import pickle

# Guarda el DataFrame de IDs y la matriz de vectores en un diccionario
movie_vectors = {
    "titles": df['title'].values,  # array de títulos
    "tfidf_matrix": tfidf_matrix   # matriz TF-IDF
}

# Guardar en archivo binario
with open('movie_vectors.pkl', 'wb') as f:
    pickle.dump(movie_vectors, f)

Lets verify it everything ok

In [105]:
# Cargar el archivo binario
with open('movie_vectors.pkl', 'rb') as f:
    movie_vectors = pickle.load(f)

# Verifica los datos cargados
print(type(movie_vectors))
print(movie_vectors.keys())  # Debería mostrar 'titles' y 'tfidf_matrix'
print(movie_vectors['titles'][:5])  # Muestra algunos títulos para verificar
print(movie_vectors['tfidf_matrix'].shape)  # Muestra la forma de la matriz de vectores

<class 'dict'>
dict_keys(['titles', 'tfidf_matrix'])
['Toy Story' 'Jumanji' 'Grumpier Old Men' 'Waiting to Exhale'
 'Father of the Bride Part II']
(45379, 82253)

Developing the apis functionality we realize that it was simpler to have only one data set file. So here we are going to combine the 3 data sets to make it easyer to work with it.

In [5]:
import pandas as pd

# Cargar los archivos originales
df_movies = pd.read_csv('./app/movies_limpio.csv')
df_cast = pd.read_csv('./app/movies_cast.csv')
df_crew = pd.read_csv('./app/movies_crew.csv')

# Convertir las columnas `id` en `df_movies` y `movie_id` en `df_cast` y `df_crew` a tipo string
df_movies = df_movies.rename(columns={"id": "movie_id"})  # Renombrar 'id' a 'movie_id' para que coincida
df_movies['movie_id'] = df_movies['movie_id'].astype(str)
df_cast['movie_id'] = df_cast['movie_id'].astype(str)
df_crew['movie_id'] = df_crew['movie_id'].astype(str)

# Agrupar y concatenar los nombres de los actores y directores
df_cast_grouped = df_cast.groupby('movie_id')['name'].apply(lambda x: ', '.join(x)).reset_index()
df_crew_grouped = df_crew.groupby('movie_id')['name'].apply(lambda x: ', '.join(x)).reset_index()

# Merge de los datos
df_merged = df_movies.merge(df_cast_grouped, on="movie_id", how="left")
df_merged = df_merged.merge(df_crew_grouped, on="movie_id", how="left")

# Renombrar las columnas para claridad
df_merged = df_merged.rename(columns={"name_x": "cast", "name_y": "crew"})

# Guardar el resultado en un nuevo CSV
df_merged.to_csv('movies_combined.csv', index=False)

C:\Users\User\AppData\Local\Temp\ipykernel_4144\318541524.py:4: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_movies = pd.read_csv('./app/movies_limpio.csv')